server.port=8082
spring.application.name=lecturer-service

# MongoDB configuration
spring.data.mongodb.uri=mongodb+srv://sakithaudarashmika63:KkdHaOWzf8PY0Xl1@mernapp.s3ekfyg.mongodb.net/mtit?appName=mernApp

# Swagger UI configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
