server:
  port: 8083

spring:
  application:
    name: enrollment-service
  data:
    mongodb:
      uri: mongodb+srv://sakithaudarashmika63:KkdHaOWzf8PY0Xl1@mernapp.s3ekfyg.mongodb.net/mtit?appName=mernApp
      database: mtit

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info

